import pygame

flechaiz = pygame.image.load("flecha izquierda.jpeg")
flechaiz = pygame.transform.scale(flechaiz,(100,100))
flechader = pygame.image.load("flecha derecha.jpeg")
flechader = pygame.transform.scale(flechader,(100,100))
flechaiz2 = pygame.image.load("flecha izquierda 2.jpeg")
flechaiz2 = pygame.transform.scale(flechaiz2,(100,100))
flechader2 = pygame.image.load("flecha derecha 2.jpeg")
flechader2 = pygame.transform.scale(flechader2,(100,100))
boton_inicio = pygame.image.load("jugar2.jpeg")
boton_inicio = pygame.transform.scale(boton_inicio,(200,100))
boton_exit = pygame.image.load("salir.jpeg")
boton_exit = pygame.transform.scale(boton_exit,(200,100))
boton_highscore = pygame.image.load("historial.jpeg")
boton_highscore = pygame.transform.scale(boton_highscore,(200,100))
boton_inicio2 = pygame.image.load("jugar.jpeg")
boton_inicio2 = pygame.transform.scale(boton_inicio2,(200,100))
boton_highscore2 = pygame.image.load("historial2.jpeg")
boton_highscore2 = pygame.transform.scale(boton_highscore2,(200,100))
boton_exit2 = pygame.image.load("salir2.jpeg")
boton_exit2 = pygame.transform.scale(boton_exit2,(200,100))